title: 'Theme Settings'
data:
  primary_colour: '#E61E2A'
  text_colour: '#575756'
  support_colour: '#F0F0F0'
  navigation_primary_colour: '#3C3C3B'
  navigation_secondary_colour: '#31302F'
  footer_background_colour: '#3C3C3B'
