title: 'Bar & Booth Layouts'
updated_by: 1
updated_at: 1687363479
blueprint: boutique_furniture_hire
seo:
  description: 'View our various bar and booth layouts here, from single to triple seat units and central to horseshoe bars, we have lots to choose from!'
