title: 'Bean Bags & Tables'
updated_by: 1
updated_at: 1687363511
blueprint: boutique_furniture_hire
seo:
  description: 'View our beanbags and various bespoke tables available for hire, from Pacman tables to champagne tables, we have it all!'
