title: 'Props & Accessories'
updated_by: 1
updated_at: 1687363586
blueprint: boutique_furniture_hire
seo:
  description: 'View our selection of props for event hire from large champagne tubs to giant playing cards, if you need it, we will have it!'
