sections:
  main:
    display: 'Primary Navigation'
    fields:
      -
        handle: company_logo
        field:
          mode: list
          container: images
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Company Logo'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          width: 50
      -
        handle: sticky
        field:
          default: false
          display: Sticky
          type: toggle
          icon: toggle
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          width: 25
      -
        handle: shrink_on_scroll
        field:
          default: false
          display: 'Shrink On Scroll'
          type: toggle
          icon: toggle
          listable: hidden
          instructions_position: above
          visibility: visible
          width: 25
