title: "Components: Products"
fields:
  - handle: components
    field:
      collapse: false
      previews: true
      sets:
        contact_us_block:
          display: "Contact Us"
          fields:
            - import: contact_us_block
      display: Components
      type: replicator
      icon: replicator
      listable: hidden
      instructions_position: above
      visibility: visible
