sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Title
          instructions_position: above
          listable: true
          visibility: visible
          input_type: text
          antlers: false
      -
        handle: product_description
        field:
          antlers: false
          display: 'Product Description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: product_images
        field:
          mode: list
          container: images
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Product Images'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: boutique_furniture_hire
        field:
          type: terms
          taxonomies:
            - boutique_furniture_hire
          display: 'Boutique Furniture Hire'
          mode: select
          instructions_position: above
          listable: true
          visibility: visible
          create: true
      -
        handle: featured_image
        field:
          mode: list
          container: images
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Featured Image'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
  contact_us_block:
    display: 'Contact Us Block'
    fields:
      -
        import: contact_us_block
        prefix: contact_us_block
title: Product
