title: Products
template: product
layout: layout
taxonomies:
  - boutique_furniture_hire
revisions: false
route: 'boutique-furniture-hire/{parent_uri}/{boutique_furniture_hire}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
structure:
  root: false
